node_js:
  - "0.10"
language: node_js
before_script: mkdir -p shippable/codecoverage
after_script: 
  - ./node_modules/.bin/istanbul cover ./node_modules/.bin/_mocha -- -u tdd 
  - ./node_modules/.bin/istanbul report cobertura --dir  shippable/codecoverage/
notifications:
  email:
    - shawnb457@gmail.com

deploy:
  provider: heroku
  api_key: "9091071b-91b9-421d-9704-3976d65f1017"

