default:
  server:
    port: 3000
  database:
    host: 'localhost'
    port: 27017
development:
  database:
    host: 'localhost'
    port: 27017
    db: 'TireAppRoles'
test:
  database:
    db: 'TireAppRoles'
production:
  server:
    port: 8000
  database:
    db: 'TireAppRoles'
    user: 'dbuser'
    password: 'pass'
  cache:
    dir: 'static'